name: textlint

on:
  push:
    branches: [ main ]

env:
  TEST_TAG: textlint-articles:1.0.0

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile

  dockle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - name: docker build
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      - uses: hands-lab/dockle-action@v1
        with:
          image: ${{ env.TEST_TAG }}

  textlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # textlintを使用するためにnode.jsの設定を行う
      - uses: actions/setup-node@v2

      - name: Install textlint
        run: >
          npm install --save-dev
          textlint@12.1.0
          textlint-rule-preset-smarthr@1.11.3
          textlint-rule-prh@5.3.0 
          textlint-filter-rule-allowlist@4.0.0
      
      - name: Install dependent module
        run: npm install
      
      - name: Execute textlint
        run: npx textlint "articles/**/*.md"
