name: textlint

on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # textlintを使用するためにnode.jsの設定を行う
      - uses: actions/setup-node@v2

      - name: Install textlint
        run: >
          npm install --save-dev
          textlint@12.1.0
          textlint-rule-preset-smarthr
          textlint-rule-prh 
          textlint-filter-rule-allowlist
      
      - name: Install dependent module
        run: npm install
      
      - name: Execute textlint
        run: npx textlint "articles/**/*.md"
